services:
  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

  backend:
    build: ./backend 
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=de_lingo_user
      - DB_PASS=de_lingo_user
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=de_lingo_boost_db
      - POSTGRES_USER=de_lingo_user
      - POSTGRES_PASSWORD=de_lingo_user
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U de_lingo_user -d de_lingo_boost_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: